# Minimum rapidfuzz token_set_ratio score to accept a fuzzy match
FUZZY_THRESHOLD: int = 75

# Resolution priority — lower index = higher priority
MATCH_ORDER: dict[str, int] = {
    "exact": 0,
    "partial": 1,
    "fuzzy": 2,
    "ip": 0,  # IP match is as authoritative as exact
}

# Tokens that carry no discriminating signal and are skipped during matching.
# These are stripped from the clause BEFORE n-gram building so they never
# anchor or fragment meaningful spans.
#
# Rules for inclusion:
#   - Word must never appear as a discriminating part of a camera/folder name
#   - Word carries no location, zone, or device signal
#   - Removing it cannot change which camera is intended
STOPWORDS: set[str] = {
    # ── Articles & determiners ────────────────────────────────────────────────
    "a",
    "an",
    "the",
    "this",
    "that",
    "these",
    "those",
    "some",
    "any",
    # ── Prepositions ──────────────────────────────────────────────────────────
    "at",
    "in",
    "on",
    "of",
    "to",
    "for",
    "by",
    "as",
    "up",
    "is",
    "from",
    "into",
    "onto",
    "upon",
    "with",
    "within",
    "without",
    "about",
    "above",
    "below",
    "under",
    "over",
    "near",
    "inside",
    "outside",
    "around",
    "between",
    "through",
    "across",
    "along",
    "behind",
    "beside",
    "beyond",
    "during",
    "before",
    "after",
    # ── Conjunctions ──────────────────────────────────────────────────────────
    "and",
    "or",
    "but",
    "nor",
    "yet",
    "so",
    "either",
    "neither",
    "both",
    "whether",
    # ── Pronouns ──────────────────────────────────────────────────────────────
    "i",
    "me",
    "my",
    "we",
    "us",
    "our",
    "you",
    "your",
    "it",
    "its",
    "they",
    "them",
    "their",
    "he",
    "she",
    "his",
    "her",
    # ── Common verbs carrying no location signal ──────────────────────────────
    "show",
    "get",
    "give",
    "find",
    "fetch",
    "pull",
    "load",
    "open",
    "display",
    "view",
    "watch",
    "play",
    "start",
    "stop",
    "check",
    "look",
    "see",
    "tell",
    "list",
    "bring",
    "need",
    "want",
    "let",
    "make",
    "take",
    "have",
    "has",
    "had",
    "was",
    "were",
    "are",
    "be",
    "been",
    "being",
    "do",
    "does",
    "did",
    "can",
    "could",
    "will",
    "would",
    "should",
    "shall",
    "may",
    "might",
    "must",
    # ── Query / instruction words ─────────────────────────────────────────────
    "all",
    "every",
    "each",
    "any",
    "which",
    "what",
    "where",
    "when",
    "who",
    "how",
    "why",
    "please",
    "just",
    "only",
    "also",
    "too",
    "now",
    "here",
    "there",
    # ── Time words (carry no camera location signal) ──────────────────────────
    "last",
    "latest",
    "recent",
    "today",
    "yesterday",
    "tonight",
    "night",
    "morning",
    "afternoon",
    "evening",
    "week",
    "month",
    "year",
    "hour",
    "minute",
    "second",
    "ago",
    "since",
    "until",
    "past",
    "current",
    "live",
    "realtime",
    "real",
    # ── Video / surveillance generic terms ────────────────────────────────────
    "footage",
    "feed",
    "video",
    "stream",
    "streaming",
    "recording",
    "recorded",
    "playback",
    "snapshot",
    "clip",
    "image",
    "frame",
    "live",
    "preview",
    # ── Generic spatial/descriptive words ────────────────────────────────────
    "happened",
    "activity",
    "event",
    "events",
    "incident",
    "alert",
    "status",
    "situation",
    "update",
    "report",
    "log",
    "logs",
    "site",
    "location",
    "place",
    "area",
    "region",
    "zone",
    "inside",
    "outside",
    "nearby",
    "adjacent",
    # ── Low-discrimination domain words in almost every node name ────────────
    "default",
    "main",
    "primary",
    "secondary",
    "general",
    "common",
    # "server"  — removed, no longer a node type
    # "cam"     — removed, carries real signal e.g. CAM01 narrows to specific camera
    # "camera"  — kept out, too generic but watch: some folders use it
}
