OPERATORS = [
    "Equal",
    "NotEqual",
    "GreaterThan",
    "SmallerThan",
    "GreaterThanOrEqual",
    "SmallerThanOrEqual",
    "Contains",
    "NotContains",
    "In",
    "NotIn",
    "Between",
    "Like",
    "NotLike",
]
